apiVersion: v2
name: database-infra
description: A Helm chart for PostgreSQL database with automatic DB provisioning
type: application
version: 1.0.0
dependencies:
  - name: postgresql
    version: 18.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
