annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Update adguard/adguardhome docker tag to v0.107.56
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/AdguardTeam/AdGuardHome
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/adguard-home
apiVersion: v2
appVersion: v0.107.56
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
description: Free and open source, powerful network-wide ads & trackers blocking DNS
  server.
home: https://charts.gabe565.com/charts/adguard-home/
icon: https://raw.githubusercontent.com/gabe565/charts/main/charts/adguard-home/icon.svg
keywords:
- adblock
- dns
- privacy
kubeVersion: '>=1.22.0-0'
name: adguard-home
sources:
- https://github.com/AdguardTeam/AdGuardHome
type: application
version: 0.3.25
