---
ca_certificates_version: "20260601~24.04.1*"
curl_version: "8.5.0-*"
git_version: "1:2.43.0-*"
htop_version: "3.3.0-*"
tar_version: "1.35+dfsg-*"
ufw_version: "0.36.2-*"
unzip_version: "6.0-*"
wget_version: "1.21.4-*"

system_packages:
  - "ca-certificates={{ ca_certificates_version }}"
  - "curl={{ curl_version }}"
  - "git={{ git_version }}"
  - "htop={{ htop_version }}"
  - "tar={{ tar_version }}"
  - "ufw={{ ufw_version }}"
  - "unzip={{ unzip_version }}"
  - "wget={{ wget_version }}"

sudoers_dir: "/etc/sudoers.d"
