---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present

- name: Configure passwordless sudo for ansible_user
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/90-{{ ansible_user | default(ansible_env.USER | default('ansible')) }}" # Use a file name based on the user
    create: true
    mode: '0440'
    owner: root
    group: root
    line: "{{ ansible_user | default(ansible_env.USER | default('ansible')) }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s' # Validate syntax before writing
  when: (ansible_become_method | default('sudo')) == 'sudo' and (ansible_user | default('')) != '' # Only apply if using sudo and user defined

- name: Ensure authorized SSH keys are present
  ansible.posix.authorized_key:
    user: "{{ ansible_user | default(ansible_env.USER | default('ansible')) }}"
    state: present
    key: "{{ item }}"
  loop: "{{ authorized_ssh_keys | default([]) }}"


- name: Enable and manage ufw
  community.general.ufw:
    state: enabled
    policy: allow # Default policy for outgoing traffic

- name: Allow incoming SSH traffic for authorized sources
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    from_ip: "{{ item.src | default(item) }}"
    comment: "{{ item.comment | default('Allow SSH access') }}"
  loop: "{{ authorized_ssh_sources | default([]) }}"


- name: Allow incoming HTTP traffic for Gateway LoadBalancer
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: 'Allow Gateway LoadBalancer HTTP'

- name: Allow incoming HTTPS traffic for Gateway LoadBalancer
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
    comment: 'Allow Gateway LoadBalancer HTTPS'

- name: Allow incoming DNS traffic (TCP)
  community.general.ufw:
    rule: allow
    port: '53'
    proto: tcp
    comment: 'Allow DNS (AdGuard Home)'

- name: Allow incoming DNS traffic (UDP)
  community.general.ufw:
    rule: allow
    port: '53'
    proto: udp
    comment: 'Allow DNS (AdGuard Home)'
