apiVersion: v2
appVersion: 1.0.0
dependencies:
- alias: main
  name: app-template
  repository: https://bjw-s-labs.github.io/helm-charts/
  version: 5.0.1
description: A Helm chart for the Servarr suite (Radarr, Sonarr, Prowlarr, Bazarr)
  and helper Flaresolverr
name: servarr
type: application
version: 0.3.0
